name: silverlinings-diagnostics-dev
channels:
    - conda-forge
    - nodefaults
dependencies:
    - numpy
    - xarray
    - matplotlib
    - cartopy
    - dask
    - jupyter
    - jupyterlab
    - netCDF4
    - ipykernel
    - ncar-jobqueue
    - intake-esm
    - pip
    - pip:
      - ecgtools
